// Централизованная конфигурация моделей медиа-генерации
import type { MediaModel } from '@/redux/api/base';

export interface ModelConfig {
    // Флаги для проверок типа модели
    isNanoBanana: boolean;
    isNanoBananaPro: boolean;
    isNanoBananaProKieai: boolean;
    isVeo: boolean;
    isKling: boolean;
    isKling25: boolean;
    isImagen4: boolean;
    isImagen4Ultra: boolean;
    isSeedream4_5: boolean;
    isSeedream4_5_Edit: boolean;
    isElevenLabs: boolean;

    // Поддерживаемые параметры
    supportsFormat: boolean;
    supportsQuality: boolean;
    supportsDuration: boolean;
    supportsSound: boolean;
    supportsVeoGenerationType: boolean;
    supportsNegativePrompt: boolean;
    supportsSeed: boolean;
    supportsCfgScale: boolean;
    supportsTailImageUrl: boolean;
    supportsElevenLabsParams: boolean;

    // Ограничения
    maxInputFiles?: number; // Максимальное количество входных файлов
}

// Конфигурация для каждой модели
const MODEL_CONFIGS: Record<MediaModel, ModelConfig> = {
    MIDJOURNEY: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: false,
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    VEO_3_1_FAST_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: true,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // videoFormat (ar)
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: true,
        supportsNegativePrompt: false,
        supportsSeed: true,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    NANO_BANANA_PRO_LAOZHANG: {
        isNanoBanana: false,
        isNanoBananaPro: true,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: true,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    SORA_2: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: false,
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    VEO_3_1_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: true,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // videoFormat (ar)
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: true,
        supportsNegativePrompt: false,
        supportsSeed: true,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    KLING_2_6_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: true,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // klingAspectRatio
        supportsQuality: false,
        supportsDuration: true,
        supportsSound: true,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    KLING_2_5_TURBO_PRO_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: true,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // klingAspectRatio
        supportsQuality: false,
        supportsDuration: true,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: true,
        supportsSeed: false,
        supportsCfgScale: true,
        supportsTailImageUrl: true,
        supportsElevenLabsParams: false,
    },
    NANO_BANANA_PRO_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: true,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: true,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    NANO_BANANA_2_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: true,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    IMAGEN4_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: true,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: true,
        supportsSeed: true,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    IMAGEN4_ULTRA_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: true,
        isImagen4Ultra: true,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: true,
        supportsSeed: true,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    SEEDREAM_4_5_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: true,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: true,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
    SEEDREAM_4_5_EDIT_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: true,
        isElevenLabs: false,
        supportsFormat: true,
        supportsQuality: true,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
        maxInputFiles: 14,
    },
    ELEVENLABS_MULTILINGUAL_V2_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: true,
        supportsFormat: false,
        supportsQuality: false,
        supportsDuration: false,
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: true,
    },
    KLING_VIDEO_O1_WAVESPEED: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // aspect_ratio
        supportsQuality: false,
        supportsDuration: true, // от 3 до 10 секунд
        supportsSound: false,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
        maxInputFiles: 10, // до 10 reference images
    },
    SEEDANCE_1_5_PRO_KIEAI: {
        isNanoBanana: false,
        isNanoBananaPro: false,
        isNanoBananaProKieai: false,
        isVeo: false,
        isKling: false,
        isKling25: false,
        isImagen4: false,
        isImagen4Ultra: false,
        isSeedream4_5: false,
        isSeedream4_5_Edit: false,
        isElevenLabs: false,
        supportsFormat: true, // aspect_ratio (16:9 или 9:16)
        supportsQuality: false,
        supportsDuration: true, // 4, 8, 12 секунд
        supportsSound: true,
        supportsVeoGenerationType: false,
        supportsNegativePrompt: false,
        supportsSeed: false,
        supportsCfgScale: false,
        supportsTailImageUrl: false,
        supportsElevenLabsParams: false,
    },
};

// Получить конфигурацию модели
export function getModelConfig(model: MediaModel): ModelConfig {
    return MODEL_CONFIGS[model];
}

// Получить все флаги модели
export function getModelFlags(model: MediaModel): ModelConfig {
    return MODEL_CONFIGS[model];
}
